### ISSUE TITLE
Add support for scheduled "lift wrist to view info"

### ISSUE THREAD

**Issue by ncartron** [piggz/harbour-amazfish#100]
When sleeping and moving, Amazfit watch wakes up as my wrist is moving, which can be annoying :)

The Android app has a nice feature to add schedule to this feature, e.g. "do not enable lift wrist to view info" between 10pm and 7am.

It would be nice to have it also in Amazfish :)

**Comment by je-nix** [comment]
As already mentioned in duplicate issue #127, this becomes an important feature with the GTS since it only displays the time when activated.
This could be implemented in two ways:
- timed schedule set in Amazfish
- if Amazfish knows about the DND state of the watch, it could be tied to DND / SmartDND being active

**Comment by je-nix** [comment]
The Zepp app (formerly Amazfit) now supports the setting to schedule the "lift wrist" time with a simple "start at x, stop at y". Since this also works when the watch is not connected to the app, it seems the schedule is stored on the watch itself and should be able to be set by Amazfish. I don't know, if this feature was added with a specific firmware version though.
