### ISSUE TITLE
GTS with new protocol

### ISSUE THREAD

**Issue by mklick** [piggz/harbour-amazfish#124]
The new firmware 0.0.9.12 installed July 1st by Amazfit introduced also a new protocol. Amazfish does not work any longer (BT pairing still works) and generates an error message at the watch that the app should be upgraded to the latest version.
Please find the BT dump enclosed, created by btsnoop under Android 7 when Amazfit communicates with the watch.
[btsnoop_hci.log](https://github.com/piggz/harbour-amazfish/files/4866900/btsnoop_hci.log)

**Comment by armorica** [comment]
I'm having the same/similar issue with my GTR. Watch is paired, data like "number of steps" is still synced, but the watch shows a "connection failed, update to the latest version of the app to synchronize data." message every so much time. 
My GTR is new, only got it yesterday and in the process of adding it to my Android phone it automatically got the updates; no way of preventing that as far as I could see.

**Comment by piggz** [comment]
according to wireshark, the log is corrupt, can you try again?

**Comment by je-nix** [comment]
I can confirm both this issue and that it is fixed in 1.6.5.

I replaced my Amazfit BIP with a GTS yesterday. After the initial pairing with 1.6.1, the notification "connection failed, update to the latest version of the app to synchronize data." was shown on the watch every time Amafish tried to connect to it. After updating to 1.6.5, this issue went away and syncing seems to work fine.
