### ISSUE TITLE
Functionality supported for GTR

### ISSUE THREAD

**Issue by armorica** [piggz/harbour-amazfish#129]
I've succesfully connected Amazfish with my GTR, but except for the number of steps and heartrate data nothing is shown, nor downloadable. Question is whether this is the amount of support for the GTR at the moment or whether I am missing something with respect to connecting the two.

As the GTR is not mentioned at all yet in the README (but appears to be pretty similar to the GTS with respect to the funtionality) I hoped to be able to get more data from the watch already.

If I can be of help by providing data/logs or whatsoever, let me know.

**Comment by je-nix** [comment]
It seems that the weather sync is currently not working correctly (see #125), though the weather app on my GTS gets updated and shows the correct forecast.
Other than that I'm not sure what functionality is missing. Can you please elaborate, which features are missing / not working?

**Comment by piggz** [comment]
Is this still an issue?

**Comment by FloM28** [comment]
Yes. I have the same problem on XA2 with amazfish > 1.6.8.  Only steps and heartrate.

[amazfish 15.02.21.txt](https://github.com/piggz/harbour-amazfish/files/5981784/amazfish.15.02.21.txt)

**Comment by je-nix** [comment]
The weather sync is working for me since the change of daylight saving time (went from GMT+2 to GMT+1), so I'd guess its some time zone related thing.
The hearth rate readings and step counter is synced to Amazfish fine. The sleep summary is always way off (accounting around 1 h of sleep when it should be 8), but that's probably the smartwatch itself being shit.

**Comment by piggz** [comment]
Sleep algorithm needs some work yes.
