### ISSUE TITLE
Possibility of an iOS build

### ISSUE THREAD

**Issue by laubblaeser** [piggz/harbour-amazfish#196]
Over on the [InfiniTime repo](https://github.com/JF002/InfiniTime/issues/486) there is currently a discussion about building an iOS companion app for the device. As far as I can see, Amazfish is built with Kirigami. It's a great cross-platform framework and its website even states that building apps with it for iOS would be possible indeed. So naturally I was wondering if anyone has tried to build Amazfish for iOS devices or if any knowledge exists among Amazfish devs in that regard? Thanks in advance for any insights. :)

**Comment by piggz** [comment]
While I imagine the UI would work ok in IOS, the issue is in the backend and architecture.  Amazfish uses a wrapper library QBLE for the BLE comms to the device, this wraps the bluez dbus api, so would need completely re-written for ios.  Also, the daemon/ui architecture relies on dbus, so i imagine this would need re-worked also.
