### ISSUE TITLE
[SailfishOS] [FP2] - Amazfish does not reconnect to Infinitime after update of OS to version 4.2

### ISSUE THREAD

**Issue by muppeth** [piggz/harbour-amazfish#203]
Updated SailfishOS to version 4.2 on Fairphone2 and noticed Infinitime not reconecting upon lost connection and when connecting by hand, it has issues connecting back. Usually I need to pair again. Connection usually drops after a while of usage (one hour or so?). 
Aparently blueZ5 package has been updated in 4.2 so  that could be the issue. I wonder if someone else has managed to reproduce that issue.

**Comment by piggz** [comment]
Someone else had a similar issue, and it was fixed by also pairing the watch in the sailfish BT settings page.  I think that also works for me, could you check if that fixes it for you?

**Comment by dvidebaek** [comment]
I have the same problem with my Pinetime on SFOS 4.4.0.68 on Sony Xperia 10 II

**Comment by krnlyng** [comment]
Hi, this is most likely related to https://github.com/sailfishos/kf5bluezqt/pull/4 and a related UI change. Until the fix is out you can pair the device from command line using the bluetoothctl command like this:

```
devel-su
bluetoothctl
agent off
agent KeyboardDisplay
scan on

# wait for the device to appear

pair BLUETOOTH_ADDRESS_OF_THE_DEVICE
```

At this point the InfiniTime will show a code that you can enter into bluetoothctl.
Afterwards the pairing should complete and the pairing should not be lost anymore.

There is another issue which can cause pairings to be lost but only applies to Xperia 10 III. The fix is here: https://github.com/mer-hybris/android_kernel_sony_msm/commit/9b858b2b0f64ee8f3d577b36591fcbb567e2d187
and the workaround until the fix is out is to run

```
devel-su
hciconfig hci0 name "Xperia 10 III"
```

after each reboot. The name can be changed depending on how you want the device to appear but should match the name set in Settings->Bluetooth.

**Comment by DrYak** [comment]
Hi,

Pairing (did it from the GUI like the first two answers) also worked for me.
Sony Xperia10iii, SFOS: 4.4.0.72 (bluez5: 5.58), Infinitime: 1.11.0, Amazfish: 2.10.

Might be worth adding to the official documentation?
