### ISSUE TITLE
Bad Bluetooth connection on SFOS 4.5

### ISSUE THREAD

**Issue by elkiaer-dk** [piggz/harbour-amazfish#255]
It is very hard to get a Bluetooth connection with the device (in my case Amazfit GTS). I have succeeded twice but then the microphone "breaks" down and it is not possible to have a phone call, the other part can not hear me.

**Comment by elkiaer-dk** [comment]
Strange.
I took the .kexi file from my phone with SFOS4.5 to my phone with SFOS4.4. No issue with connecting, could see actual steps and pulz but couldn't download any data. 
I then open my SFOS4.5 and could now  connect without any issues. Could also download latest date. Further I test the microphone and was able to make phone calls.

**Comment by fabio-87** [comment]
Same here. Very hard to get bluetooth connection with my GTR 2 and Sailfish 4.5.0.18/19 (actually). When successfully connected all works well, but it's very hard to connect, it takes so many tries to make you nervous and directly turn off the Bluetooth 😆.

**Comment by drwakey** [comment]
Hmm, i cannot find my MiBand6 with Amazfish, but i dont know if it is just because its protocol is different from the MiBand4 or because it is the same problem described here.
SFOS4.5 on Xperia XA2 🤔

If i search the Band via SFOS directly it is no problem to find and connect it, but Amazfish will still not recognize it 🤔
